# Project
[project]
name = "vultr-python"
description = "Python 3 wrapper for the Vultr API v2.0"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [{ name = "Shane" }]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
]
# license = { file = "LICENSE" }
dependencies = ["requests"]
dynamic = ["version"]

[project.urls]
Changelog = "https://github.com/cssnr/vultr-python/releases"
Discord = "https://discord.gg/wXy6m2X8wY"
Documentation = "https://cssnr.github.io/vultr-python/"
Funding = "https://ko-fi.com/cssnr"
GitHub = "https://github.com/cssnr/vultr-python"
Homepage = "https://cssnr.com/"
Issues = "https://github.com/cssnr/vultr-python/issues"

[dependency-groups]
dev = [
  "bandit",
  "black",
  "build",
  "coverage",
  "isort",
  "mypy",
  "pytest",
  "requests",
  "ruff",
  "setuptools",
  "tombi; python_version>='3.10'",
  "toml-run",
  "ty",
  "types-requests",
  "validate-pyproject[all]",
  "watchdog[watchmedo]",
]

# Build System
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# Bandit
# https://bandit.readthedocs.io/en/latest/config.html
[tool.bandit]
exclude_dirs = ["venv"]
skips = ["B105", "B107"]
assert_used = { skips = ["*test_*.py"] }

# Black
# https://black.readthedocs.io/en/stable/usage_and_configuration/
[tool.black]
line-length = 119
extend-exclude = '(\.github)'

# Coverage
# https://coverage.readthedocs.io/en/latest/
[tool.coverage.run]
omit = ["*.egg-info/*", ".github/*"]
source = ["src"]

# Isort
# https://pycqa.github.io/isort/docs/configuration/options.html
[tool.isort]
profile = "black"
src_paths = ["src", "test"]
skip = ["venv", ".github"]

# Mypy
# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
# ignore_missing_imports = true
exclude = ["venv"]

# Ruff
# https://docs.astral.sh/ruff/configuration/
[tool.ruff]
line-length = 119
target-version = "py313"
extend-exclude = [".github"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "Q"]

# Scripts
# https://github.com/cssnr/toml-run
[tool.scripts]
test = ["coverage run -m pytest", "coverage report -m"]
# clean = "rm -rf dist"
build = "python -m build"
docs = "python -m pdoc -t docs -p 8000 -h 0.0.0.0 --logo https://raw.githubusercontent.com/cssnr/vultr-python/refs/heads/master/.github/assets/logo.svg --logo-link https://github.com/cssnr/vultr-python /src/vultr"
docs-watch = 'watchmedo auto-restart -R -d docs -p "*.*" -- run docs'
format = [
  "black .",
  "isort -c .",
  "ruff format",
  "tombi format",
  "which prettier && prettier --write . || echo missing prettier",
]
lint = [
  "run bandit",
  "run mypy",
  "run ruff",
  "run validate",
  "run yamllint",
  "which prettier && prettier --check . || echo missing prettier",
  "black --check .",
  "isort -c .",
  "tombi lint",
  "ty check -v .",
]
bandit = "bandit -c pyproject.toml -r ."
mypy = "mypy ."
ruff = "ruff check ."
validate = "validate-pyproject pyproject.toml"
yamllint = "yamllint -c .github/yamllint.yaml ."

# Setup Tools
[tool.setuptools.package-data]
vultr = ["py.typed"]

[tool.setuptools.dynamic]
version = { attr = "vultr.version.__version__" }
