name: "GitHub Pages"

on:
  release:
    types: [published]
#  workflow_dispatch:
#    environment:
#      type: choice
#      description: Choose Environment
#      options:
#        - testpypi
#        - pypi
  push:

env:
  ENVIRONMENT: "testpypi"
  REPOSITORY: "https://test.pypi.org/legacy/"

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'release' && !github.event.release.prerelease

    permissions:
      id-token: write

    environment:
      name: ${{ env.ENVIRONMENT }}
      url: https://pypi.org/project/vultr-python/

    steps:
      - name: "PyPi Publish"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ env.REPOSITORY }}
